spring.application.name=Task_DATA_JPA_INTEGRATION_FROM_OUTSIDE


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-2.c768a6u48f82.ap-south-1.rds.amazonaws.com:3306/courses
spring.datasource.username=gani
spring.datasource.password=gani1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


